### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by unstoppablecarl** [boxedcode/laravel-eloquent-meta#3]
I see some areas that I think I could improve. For example the `Registry` class could be simplified by using the built in service container. Would you be receptive to pull requests?

**Comment by olsgreen** [comment]
Sure. Always open to improvements, although by saying that I'm not 100% guaranteeing pulls.

I'd have to see an implementation or more detail on the Registry idea to comment.

**Comment by unstoppablecarl** [comment]
Can you follow me back on twitter or email me? I have some questions and ideas I want to discuss.
